[package]
name = "sepulcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
murmur3 = "0.5.1"
twox-hash = "1.6.3"
rand = "0.8"
byteorder = "1.4.3"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }